CCProAPI/urls.py
from django.urls import path

from . import views

app_name = 'CCProAPI'

# "name":"bitcoin",
# "amount":"1.0125",
# "price":"1200",
# "convert":"EUR"

urlpatterns = [
    path('api', views.evaluate_portfolio, name='api'),
    # url(r'^api/$', views.evaluate_portfolio, name='snippet-list'),
    # url(r'^api/(?P<pk>[0-9]+)/highlight/$', snippet_highlight, name='snippet-highlight'),
    # path('^(?P<pk>[0-9]+)/$', views., name='index'),
    # url(r'^snippets/(?P<pk>[0-9]+)/$', views.snippet_detail),

]

CCProApp/urls.py
from django.urls import path

from . import views

app_name = 'CCProApp'

urlpatterns = [
    path('', views.select_currencies, name='index'),
    path('forms', views.select_currencies, name='selection'),
    path('ajax/select_currency', views.select_currencies_item, name='select_item'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('selection_submit', views.selection_submit, name='selection_submit'),
]

CCProfessional/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('CCProApp.urls')),
    path('CCProApp/', include('CCProApp.urls')),
    path('CCProPortfolio/', include('CCProPortfolio.urls')),
    path('CCProfessional/', include('CCProAPI.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

# ... the rest of your URLconf here ...

CCProApp/models.py
from django.db import models

# Create your models here.

CCProApp/views.py
# Create your views here.


from django.shortcuts import render, render_to_response
from django.http import HttpResponse, JsonResponse
from django.template import Context, loader
import json, requests
import os

currencies = requests.get('https://api.coinmarketcap.com/v1/ticker/')
# currencies = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),'CCProPortfolio/static/CCProPortfolio/coinmarketcap.json')).read()
rates = requests.get('http://apilayer.net/api/live?access_key=cd1747e1d9ea0ba51a5771aea42cc7d4&currencies=EUR,CZK&source=USD&format=1')
# rates = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),'CCProPortfolio/static/CCProPortfolio/apilayer.json')).read()

def select_currencies(request):
    template = loader.get_template('CCProApp/select_currencies.html')
    currenciesJson = json.loads(currencies.text)
    # currenciesJson = json.loads(currencies)
    context = {
        'cryptocurrencies' : currenciesJson,
    }
    return HttpResponse(template.render(context, request))


def select_currencies_item(request):
    formId = int(request.GET['formId']) + 1
    template = loader.get_template('CCProApp/select_currencies_item.html')
    currenciesJson = json.loads(currencies.text)
    # currenciesJson = json.loads(currencies)
    context = {
        'cryptocurrencies' : currenciesJson,
        'formId' : formId,
    }
    return HttpResponse(template.render(context, request))


def portfolio(request):
    template = loader.get_template('CCProApp/portfolio_default.html')
    currenciesJson = json.loads(currencies.text)
    # currenciesJson = json.loads(currencies)
    context = {
        'cryptocurrencies' : currenciesJson,
    }
    return HttpResponse(template.render(context, request))


def selection_submit(request):
    try:
        selected_choice = request.GET['currency']
        choices = request.GET
    except (KeyError):
        # Redisplay the question voting form.
        return select_currencies(request)
    else:
        print(selected_choice)
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return portfolio(request)

CCProApp/templates/CCProApp/select_currencies.html
{% load static %}<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Select currencies{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'CCProApp/style.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
<!-- Header -->
<div class="header-wrap d-none d-md-block">
    <div class="container">
        <div class="row">

            <!-- Left header box -->
            <header class="col-6 text-left">
                <h1>Welcome at CC Professional</h1>
            </header>

        </div>
    </div>
</div>

<!-- Main content area -->
<main class="container">
    <h2 class="article-title">The site which helps you to manage your crypto currency
        portfolio</h2><br>

    {% block content %}
        <h3>Select currencies in your portfolio</h3><br>
        <div id="form">

            <form method="GET" id="cc_form" action="{% url 'CCProApp:selection_submit' %}">
                {% include "CCProApp/select_currencies_item.html" with formId="1" %}
            </form>
            <button type="submit" form="cc_form" value="Submit" formaction="/CCProPortfolio/index" class="btn btn-primary">Submit</button>

        </div>
    {% endblock %}
</main>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% block javascript %}
    <script>

        var formsCount = 1;

        /**
         *
         * @param formIdJS id of the form that was clicked at
         */
        function currencySelected(formIdJS) {
            $.get('/CCProApp/ajax/select_currency', {
                'formId': formIdJS
            }, function (result) {
                if (formIdJS === formsCount) {
                    {#alert("formIdJS: " + formIdJS)#}
                    {#alert("forms: " + formsCount)#}
                    formsCount++;
                    $('#cc_form').append(result);
                }
            }, 'html');

        }

    </script>
{% endblock %}
</body>
</html>

CCProApp/templates/CCProApp/select_currencies_item.html
<div class="row">
    <div class="col">
        Currency name: <select name="currency_{{ formId }}" id="currency_{{ formId }}"
                               onclick="currencySelected({{ formId }})">
        <option value=" ">-</option>
        {% for c in cryptocurrencies %}
            <option value="{{ c.name }}" id="name_{{ formId }}">{{ c.name }}</option>
        {% endfor %}
    </select><br>
        Amount: <input type="number" id="amount_{{ formId }}" name="amount_{{ formId }}" step="0.1"
                       value="{{ amount_formId }}">&nbsp;&nbsp;&nbsp;pcs<br>
        Price: <input type="number" id="price_{{ formId }}" name="price_{{ formId }}" step="0.1">&nbsp;&nbsp;&nbsp;$<br>
        <br>
    </div>
</div>